---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-app-secret
type: Opaque
data:
  BGG_DB_USER: cm9vdA==
  BGG_DB_HOST: YmdnZGItc3ZjLmJnZ25zLnN2Yy5jbHVzdGVyLmxvY2Fs
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: bgg-app-po
  template:
    metadata:
      name: bgg-app-po
      labels:
        name: bgg-app-po
    spec:
      containers:
      - name: bgg-app-container
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: bgg-app-secret
        ports:
        - name: bgg-app-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    name: bgg-app-po
  ports:
  - port: 80
    targetPort: bgg-app-port