---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-app-cm
  labels:
    name: bgg-app-cm
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local


---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-app-secret
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      name: bgg-app-po
  template:
    metadata:
      name: bgg-app-po
      labels:
        name: bgg-app-po
    spec:
      containers:
      - name: bgg-app-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bgg-app-cm
        - secretRef:
            name: bgg-app-secret
        ports:
        - name: bgg-app-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    name: bgg-app-po
  ports:
  - port: 80
    targetPort: bgg-app-port